name: Build and deploy Powershell project to Azure Function App - cipp

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'  # path to your function app code

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Azure Function App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'cipp-amh5dwdwhhgeaj5'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CIPP }}
